package duan1_trieundqph05989.entity;
// Generated Aug 20, 2019 10:06:31 AM by Hibernate Tools 5.2.11.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Benhnhan generated by hbm2java
 */
@Entity
@Table(name = "Benhnhan", schema = "dbo", catalog = "qlpk_duan1")
public class Benhnhan implements java.io.Serializable {

	private String mabn;
	private String tenbn;
	private boolean gioitinh;
	private String ngaysinh;
	private Set<Phieukham> phieukhams = new HashSet<Phieukham>(0);

	public Benhnhan() {
	}

	public Benhnhan(String mabn, String tenbn, boolean gioitinh, String ngaysinh) {
		this.mabn = mabn;
		this.tenbn = tenbn;
		this.gioitinh = gioitinh;
		this.ngaysinh = ngaysinh;
	}

	public Benhnhan(String mabn, String tenbn, boolean gioitinh, String ngaysinh,
			Set<Phieukham> phieukhams) {
		this.mabn = mabn;
		this.tenbn = tenbn;
		this.gioitinh = gioitinh;
		this.ngaysinh = ngaysinh;
		this.phieukhams = phieukhams;
	}

	@Id

	@Column(name = "Mabn", unique = true, nullable = false, length = 15)
	public String getMabn() {
		return this.mabn;
	}

	public void setMabn(String mabn) {
		this.mabn = mabn;
	}

	@Column(name = "Tenbn", nullable = false)
	public String getTenbn() {
		return this.tenbn;
	}

	public void setTenbn(String tenbn) {
		this.tenbn = tenbn;
	}

	@Column(name = "Gioitinh", nullable = false)
	public boolean isGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(boolean gioitinh) {
		this.gioitinh = gioitinh;
	}

	@Column(name = "Ngaysinh", nullable = false)
	public String getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(String ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benhnhan")
	public Set<Phieukham> getPhieukhams() {
		return this.phieukhams;
	}

	public void setPhieukhams(Set<Phieukham> phieukhams) {
		this.phieukhams = phieukhams;
	}

}
