package duan1_trieundqph05989.entity;
// Generated Aug 20, 2019 10:06:31 AM by Hibernate Tools 5.2.11.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name = "Nhanvien", schema = "dbo", catalog = "qlpk_duan1")
public class Nhanvien implements java.io.Serializable {

	private String manv;
	private String tennv;
	private String taikhoan;
	private String matkhau;
	private Byte chucvu;
	private Set<Phongkham> phongkhams = new HashSet<Phongkham>(0);

	public Nhanvien() {
	}

	public Nhanvien(String manv, String tennv, String taikhoan, String matkhau) {
		this.manv = manv;
		this.tennv = tennv;
		this.taikhoan = taikhoan;
		this.matkhau = matkhau;
	}

	public Nhanvien(String manv, String tennv, String taikhoan, String matkhau, Byte chucvu,
			Set<Phongkham> phongkhams) {
		this.manv = manv;
		this.tennv = tennv;
		this.taikhoan = taikhoan;
		this.matkhau = matkhau;
		this.chucvu = chucvu;
		this.phongkhams = phongkhams;
	}

	@Id

	@Column(name = "Manv", unique = true, nullable = false, length = 20)
	public String getManv() {
		return this.manv;
	}

	public void setManv(String manv) {
		this.manv = manv;
	}

	@Column(name = "Tennv", nullable = false)
	public String getTennv() {
		return this.tennv;
	}

	public void setTennv(String tennv) {
		this.tennv = tennv;
	}

	@Column(name = "Taikhoan", nullable = false, length = 20)
	public String getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(String taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "Matkhau", nullable = false, length = 20)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@Column(name = "Chucvu")
	public Byte getChucvu() {
		return this.chucvu;
	}

	public void setChucvu(Byte chucvu) {
		this.chucvu = chucvu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvien")
	public Set<Phongkham> getPhongkhams() {
		return this.phongkhams;
	}

	public void setPhongkhams(Set<Phongkham> phongkhams) {
		this.phongkhams = phongkhams;
	}

}
