package duan1_trieundqph05989.entity;
// Generated Aug 20, 2019 10:06:31 AM by Hibernate Tools 5.2.11.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phieukham generated by hbm2java
 */
@Entity
@Table(name = "Phieukham", schema = "dbo", catalog = "qlpk_duan1")
public class Phieukham implements java.io.Serializable {

	private Integer maphieukham;
	private Benhnhan benhnhan;
	private Phongkham phongkham;
	private String ngaykham;
	private String huongdieutri;
	private Boolean donthuoc;
	private String chandoan;

	public Phieukham() {
	}

	public Phieukham(Benhnhan benhnhan, String ngaykham) {
		this.benhnhan = benhnhan;
		this.ngaykham = ngaykham;
	}

	public Phieukham(Benhnhan benhnhan, Phongkham phongkham, String ngaykham, String huongdieutri,
			Boolean donthuoc, String chandoan) {
		this.benhnhan = benhnhan;
		this.phongkham = phongkham;
		this.ngaykham = ngaykham;
		this.huongdieutri = huongdieutri;
		this.donthuoc = donthuoc;
		this.chandoan = chandoan;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Maphieukham", unique = true, nullable = false)
	public Integer getMaphieukham() {
		return this.maphieukham;
	}

	public void setMaphieukham(Integer maphieukham) {
		this.maphieukham = maphieukham;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mabn", nullable = false)
	public Benhnhan getBenhnhan() {
		return this.benhnhan;
	}

	public void setBenhnhan(Benhnhan benhnhan) {
		this.benhnhan = benhnhan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Maphongkham")
	public Phongkham getPhongkham() {
		return this.phongkham;
	}

	public void setPhongkham(Phongkham phongkham) {
		this.phongkham = phongkham;
	}

	@Column(name = "Ngaykham", nullable = false)
	public String getNgaykham() {
		return this.ngaykham;
	}

	public void setNgaykham(String ngaykham) {
		this.ngaykham = ngaykham;
	}

	@Column(name = "Huongdieutri")
	public String getHuongdieutri() {
		return this.huongdieutri;
	}

	public void setHuongdieutri(String huongdieutri) {
		this.huongdieutri = huongdieutri;
	}

	@Column(name = "Donthuoc")
	public Boolean getDonthuoc() {
		return this.donthuoc;
	}

	public void setDonthuoc(Boolean donthuoc) {
		this.donthuoc = donthuoc;
	}

	@Column(name = "Chandoan")
	public String getChandoan() {
		return this.chandoan;
	}

	public void setChandoan(String chandoan) {
		this.chandoan = chandoan;
	}

}
